### ISSUE TITLE
I cannot get it to work

### ISSUE THREAD

**Issue by Pancho111** [Stadly/TempoWiki#1]
Hi, 
I cannot get this script to work
I am using a macbook pro
I already have the appkey , what should i do with it ?
thanks

**Comment by Stadly** [comment]
Hello @calixto111,
Unfortunately, as of 29 October 2014, Spotify is no longer shipped with the Apps API [[ref]](https://developer.spotify.com/technologies/apps/). Therefore TempoWiki will not run on recent versions of Spotify. Which version of Spotify are you using?

**Comment by Pancho111** [comment]
thank you for getting back to me

version 1.0.45.186.g3b5036d6


Thanks












Thank You,



________________________________

**Comment by Stadly** [comment]
The latest version of Spotify that supports the Apps API is version 0.9.15.27. You'll have to install this version to be able to use TempoWiki.

**Comment by calixto111** [comment]
Good , I have a macbook pro computer, if I install that one , how do I avoid the spotify from upgrading ?

is there anyway ?


Thanks












Thank You,


Sales Manager:  Fabiola Acuna
Calyani Electronics, LLC







3248 NW 72nd ave Miami, fl 33122
www.calyani.com
E-mail: info@calyani.com
Tel: (305) 591-9199
Cel: (305) 796-1166




________________________________

**Comment by Pancho111** [comment]
ok  , I just installed the old version  ver 0.8.5. created the spotify folder 
Put TempoWiki folder inside spotify folder 
and I get Missing Dependencies when i type "spotify:app:tw" 
Framework compatible with api (version 1.10.2) does not exist
Can you please help me with with one?

thanks

**Comment by Stadly** [comment]
Try using version 0.9.15.27 and see if that helps. It seems like it is available for macOS at [FileHippo](http://filehippo.com/mac/download_spotify_for_mac/59584/).

**Comment by Pancho111** [comment]
I am sorry to bother you too much , I got v 0.9.15.27 ,but I have to block spotify from updating to the new software , and I have noticed that blocking spotify from updating does not let the script work .

thanks

**Comment by Stadly** [comment]
What did you do to block the updating?

**Comment by Pancho111** [comment]
I use this one

**Comment by Stadly** [comment]
That looks ok to me.

Do you get an error message when typing in `spotify:app:tw`? What does it say, exactly?

**Comment by Pancho111** [comment]
hi, 
no , I am not getting an error message , it is working ,but not showing bpm info , just try it ... it is not working any longer
let me know please 

thanks

**Comment by Stadly** [comment]
So TempoWiki shows the loading icon, but it never disappears?

**Comment by Pancho111** [comment]
Here you are ,

**Comment by Pancho111** [comment]
.

**Comment by Pancho111** [comment]
check the app I don't think is working anymore 
thanks

**Comment by Stadly** [comment]
Thanks for the details. I've found out what's wrong, but not how I can fix it yet. I'm going on holiday today, and will be back in a week. I'll fix it when I'm back and let you know here. Just out of curiosity, what are you planning on using TempoWiki for? :)

**Comment by Pancho111** [comment]
Hi,
I just need to get the bpm of the songs , 
I would like to listen to songs with the same bpm or tempo
look I have my website , but I cannot get the tempo or bpm for some reason

check it out please

http://www.calyani.com/watsonbox/exportify/master/exportify.html'

thanks

**Comment by Pancho111** [comment]
by the way , just out of curiosity , how can I learn this kind of programming , what is the name of this coding , where can I lean or study it ?
any book you recommend If it is not too much to ask

thanks

**Comment by Stadly** [comment]
Sorry this took so long. The API (The Echo Nest) I used for collecting tempo information had been shut down. I have now updated the TempoWiki to use another API (Spotify Web API). Please download and set up the app again. Then it should be working :)

TempoWiki is written using PHP and JavaScript. I'm self-taught in these languages, so unfortunately I don't know any good books to recommend.
